version: '3.7'

services:

  belfort-react:
    container_name: belfort-react
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3004:3004
    environment:
      - CHOKIDAR_USEPOLLING=true